### ISSUE TITLE
Day 1 [Cascading, 시맨틱 태그]

### ISSUE THREAD

**Issue by yoorli** [only-death/TI#1]
- CSS의 Cascading에 대해 설명해 주세요.
- 시맨틱 태그를 사용하면 좋은 점을 설명해 주세요.

논의 주제, 질문 거리, 정리한 내용이 있으면 아래 댓글로 달아주세요

**Comment by mozzi34** [comment]
📝 [1,2] Cascading, 시맨틱 태그
```
:memo: [1,2] Cascading, 시맨틱 태그
```

**Comment by yoorli** [comment]
1. css cascading 규칙에 대해 설명하시오.
2. 명시도가 무엇인지 설명하시오.
3. 시맨틱 태그의 이점을 본인의 경험에 풀어서 설명하시오.

**Comment by mozzi34** [comment]
1. 예시 부족
2. Cascading의 규칙 설명

**Comment by claudia99503** [comment]
1. 기술 면접에 적합하지 않은 단순 내용 정리 형식
2. 예시 => 면접 형식에 맞게
